version: '2'

services:
  fronetend:
    build: ./fronetend

    ports:
      - "8082:8082"
    depends_on:
      - yolo5
      - mongo

  yolo5:
    build: ./yolo5
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "8081:8081"

  mongo:
    image: "mongo"

    restart: always




